- name: Debug deploy values
  run: |
    echo "---- DEBUG DEPLOY VALUES ----"
    echo "LOCAL DIR: ./client/dist/"
    echo "SERVER DIR: /"
    echo "PORT: 21"
    echo "FTP_SERVER set? -> ${{ secrets.FTP_SERVER != '' }}"
    echo "FTP_USERNAME set? -> ${{ secrets.FTP_USERNAME != '' }}"
    echo "FTP_PASSWORD set? -> ${{ secrets.FTP_PASSWORD != '' }}"

- name: DNS lookup test
  run: nslookup ftp.b2bgoa.com
